import { Button } from "@/components/ui/button";
import { useNavigate, Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const TermsOfService = () => {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-background p-8 flex flex-col items-center">
            <div className="w-full max-w-3xl space-y-8">
                <div className="flex items-center justify-between">
                    <Button variant="ghost" onClick={() => navigate(-1)} className="gap-2 pl-0 hover:bg-transparent hover:text-primary">
                        <ArrowLeft className="w-4 h-4" /> Back
                    </Button>
                </div>

                <div className="space-y-6 text-foreground">
                    <h1 className="text-5xl font-serif tracking-tight">Terms of Service</h1>
                    <p className="text-sm text-muted-foreground">Last updated: March 5, 2026</p>

                    <div className="prose dark:prose-invert max-w-none space-y-6 text-lg leading-relaxed text-muted-foreground">

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">1. Acceptance of Terms</h2>
                            <p>
                                By accessing or using EldersFive ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">2. Description of Service</h2>
                            <p>
                                EldersFive is a debate platform where two parties present their arguments and receive AI-powered judgments from five virtual elders. The service includes real-time chat, AI-generated scoring via the Win-O-Meter, and conversation history.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">3. User Accounts</h2>
                            <ul className="space-y-2 list-disc list-inside">
                                <li>You must sign in with a valid Google account to use the Service.</li>
                                <li>You are responsible for maintaining the security of your account.</li>
                                <li>You must be at least 13 years old to use the Service.</li>
                                <li>You may not create accounts for the purpose of abusing the Service.</li>
                            </ul>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">4. Acceptable Use</h2>
                            <p>You agree not to use the Service to:</p>
                            <ul className="space-y-2 list-disc list-inside">
                                <li>Harass, threaten, or intimidate other users</li>
                                <li>Post content that is illegal, harmful, or violates the rights of others</li>
                                <li>Attempt to manipulate or game the AI judgment system</li>
                                <li>Interfere with or disrupt the Service or its infrastructure</li>
                                <li>Impersonate another person or entity</li>
                                <li>Use the Service for any commercial purpose without prior consent</li>
                            </ul>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">5. Content</h2>
                            <p>
                                You retain ownership of the content you submit to the Service. By submitting content, you grant EldersFive a non-exclusive, worldwide license to use, process, and display your content solely for the purpose of providing the Service, including generating AI judgments.
                            </p>
                            <p>
                                We reserve the right to remove content that violates these terms or is otherwise objectionable.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">6. AI Judgments</h2>
                            <p>
                                The EldersFive AI judgments are generated by language models and are provided for entertainment and informational purposes only. They do not constitute legal advice, professional mediation, or binding arbitration. You acknowledge that AI-generated judgments may contain errors or biases.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">7. Privacy</h2>
                            <p>
                                Your use of the Service is also governed by our{" "}
                                <Link to="/privacy" className="text-primary hover:underline transition-colors">
                                    Privacy Policy
                                </Link>
                                , which describes how we collect, use, and protect your information.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">8. Disclaimers</h2>
                            <p>
                                The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not guarantee that the Service will be uninterrupted, secure, or error-free.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">9. Limitation of Liability</h2>
                            <p>
                                To the maximum extent permitted by law, EldersFive shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">10. Termination</h2>
                            <p>
                                We reserve the right to suspend or terminate your account at any time for violation of these terms or for any other reason at our sole discretion. You may also delete your account at any time by contacting us.
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">11. Changes to Terms</h2>
                            <p>
                                We may update these Terms of Service from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms. We will post the revised terms on this page with an updated "Last updated" date.
                            </p>
                        </section>

                        <section className="pt-4 border-t border-border space-y-3">
                            <h2 className="text-2xl font-semibold text-foreground">12. Contact Us</h2>
                            <p>
                                If you have questions about these Terms of Service, please contact us at{" "}
                                <a
                                    href="mailto:aditya9@alumni.iitm.ac.in"
                                    className="text-primary hover:underline transition-colors"
                                >
                                    aditya9@alumni.iitm.ac.in
                                </a>
                            </p>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
