// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpurxogontbuaxmcsjls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdXJ4b2dvbnRidWF4bWNzamxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjU1OTcsImV4cCI6MjA3NTUwMTU5N30.FvfNmwgItir8vmdTfSREQ4PntB8s8iP3oAWoHLNMmpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});